Services & Brokers
socious-io/shin-api pull request #8
Opened 2024-09-08 17:10 UTC by mohammadhb

feat: Add service broker
feat: Add Email Service
feat: Integrate Email Service into Auth
fix: Converted "Sync" Services to "Async" and Renamed "Sync" Services to Libs

2024-09-09 03:02 UTC, jeyem commented on src/lib/upload.go
> +func InitS3Lib() {
make this independent from other packages even config

2024-09-09 03:02 UTC, jeyem commented on src/services/mail.go
> +	Approach    string // [template|direct]
make constant and enum for all members like this , refer to models enums

2024-09-09 21:46 UTC, mohammadhb commented
✅ Applied all of the change requests

2024-09-10 05:42 UTC, jeyem requested changes
CI&CD need to change to running consumers and related services

2024-09-10 15:34 UTC, mohammadhb commented
✅ Done 
✅ @jeyem Also put all of the channels under shin/${channel} so that it socious-api wont confuse it with its cahnnels

2024-09-17 05:52 UTC, jeyem approved these changes

2024-09-17 05:54 UTC, merged